version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./build/Dockerfile
    volumes: # マウントディレクトリ
      - ./:/go/src/app
    tty: true # コンテナの永続化
    env_file: # .envファイル
      - ./build/.go_env
    environment:
      - TZ=Asia/Tokyo
